// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHYzojd5CQ59RQr9HSB1bE12dwiQNUqys',
    appId: '1:562889962588:web:52cdf6a2a41eb2d179e299',
    messagingSenderId: '562889962588',
    projectId: 'autenticacao-teste-3af55',
    authDomain: 'autenticacao-teste-3af55.firebaseapp.com',
    storageBucket: 'autenticacao-teste-3af55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YwlkUTYk_FzIgElqnmCc2geZ1-Bfo_k',
    appId: '1:562889962588:android:6852c026590b563979e299',
    messagingSenderId: '562889962588',
    projectId: 'autenticacao-teste-3af55',
    storageBucket: 'autenticacao-teste-3af55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs0Msg-LunYhDOQTQDwcr-hbXRAXxjw2c',
    appId: '1:562889962588:ios:4087963608d2648e79e299',
    messagingSenderId: '562889962588',
    projectId: 'autenticacao-teste-3af55',
    storageBucket: 'autenticacao-teste-3af55.appspot.com',
    iosClientId: '562889962588-46iubc2cqlcfv1r4lirn47v28rkqgt9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs0Msg-LunYhDOQTQDwcr-hbXRAXxjw2c',
    appId: '1:562889962588:ios:4087963608d2648e79e299',
    messagingSenderId: '562889962588',
    projectId: 'autenticacao-teste-3af55',
    storageBucket: 'autenticacao-teste-3af55.appspot.com',
    iosClientId: '562889962588-46iubc2cqlcfv1r4lirn47v28rkqgt9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
